# Generated by Django 4.2.25 on 2025-10-16 05:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Tiêu đề văn bản')),
                ('document_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Số hiệu văn bản')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Ngày ban hành')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Ngày có hiệu lực')),
                ('source_file', models.CharField(max_length=255, verbose_name='Tên file gốc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Văn bản Luật',
                'verbose_name_plural': 'Các Văn bản Luật',
            },
        ),
        migrations.CreateModel(
            name='LawProvision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_info', models.CharField(blank=True, max_length=500, null=True, verbose_name='Thông tin Chương')),
                ('section_info', models.CharField(blank=True, max_length=500, null=True, verbose_name='Thông tin Mục')),
                ('article_number', models.IntegerField(verbose_name='Số Điều')),
                ('article_title', models.CharField(max_length=1000, verbose_name='Tiêu đề Điều')),
                ('provision_id', models.CharField(blank=True, help_text="Ví dụ: '1', '2', '3.a', '3.b'", max_length=50, null=True, verbose_name='Số Khoản/Điểm')),
                ('content', models.TextField(verbose_name='Nội dung chính')),
                ('status', models.CharField(choices=[('ACTIVE', 'Có hiệu lực'), ('AMENDED', 'Được sửa đổi'), ('REPEALED', 'Bị bãi bỏ')], default='ACTIVE', max_length=20, verbose_name='Trạng thái hiệu lực')),
                ('modification_note', models.TextField(blank=True, help_text='Ví dụ: Sửa đổi, bổ sung bởi Luật số 76/2025/QH15', null=True, verbose_name='Ghi chú sửa đổi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='chatbot.lawdocument', verbose_name='Thuộc văn bản')),
            ],
            options={
                'verbose_name': 'Điều/Khoản Luật',
                'verbose_name_plural': 'Các Điều/Khoản Luật',
                'ordering': ['document', 'article_number', 'id'],
                'unique_together': {('document', 'article_number', 'provision_id')},
            },
        ),
    ]
